### ISSUE TITLE
Mod Loading Error version 1.15.2

### ISSUE THREAD

**Issue by KihakuGato** [ReallySub/Weeping-Angels-Mod#128] opened 2020-10-08 01:29 UTC
This is the first time I've ever filed an mod-related issue so please excuse my inexpereience. If more information is needed please let me know.

message a little upon launcing with the mod present was "Weeping Angels (weeping_angels) encountered an error during create_registries event phase"
latest.log was the following

"
[07Oct2020 21:15:26.792] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, KihakuGato, --version, MultiMC5, --gameDir, C:/Users/Bryan/Desktop/MultiMC/instances/weeping Angels Bug Test/.minecraft, --assetsDir, C:/Users/Bryan/Desktop/MultiMC/assets, --assetIndex, 1.15, --uuid, 85c8d98bb10648a09851aaeeabf0870e, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.0, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601, --width, 854, --height, 480]
[07Oct2020 21:15:26.798] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_261 by Oracle Corporation
[07Oct2020 21:15:27.604] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[07Oct2020 21:15:27.658] [main/WARN] [net.minecraftforge.fml.loading.FMLConfig/CORE]: Configuration file C:\Users\Bryan\Desktop\MultiMC\instances\weeping Angels Bug Test\.minecraft\config\fml.toml is not correct. Correcting
[07Oct2020 21:15:27.666] [main/WARN] [net.minecraftforge.fml.loading.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[07Oct2020 21:15:29.317] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, C:\Users\Bryan\Desktop\MultiMC\instances\weeping Angels Bug Test\.minecraft, --assetsDir, C:\Users\Bryan\Desktop\MultiMC\assets, --uuid, 85c8d98bb10648a09851aaeeabf0870e, --username, KihakuGato, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480]
[07Oct2020 21:15:31.451] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: KihakuGato
[07Oct2020 21:15:36.590] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[07Oct2020 21:15:37.906] [modloading-worker-1/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 31.2.0, for MC 1.15.2 with MCP 20200515.085601
[07Oct2020 21:15:37.906] [modloading-worker-1/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v31.2.0 Initialized
[07Oct2020 21:15:38.146] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: class me.swirtzly.minecraft.angels.client.poses.AngelPoses onRegisterNewRegistries(Lnet/minecraftforge/event/RegistryEvent$NewRegistry;)V
		2: LOWEST
		3: ASM: me.swirtzly.minecraft.angels.WeepingAngels@56c65fc8 onNewRegistries(Lnet/minecraftforge/event/RegistryEvent$NewRegistry;)V
java.lang.NoSuchMethodError: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	at me.swirtzly.minecraft.angels.common.WAObjects$Sounds.<clinit>(WAObjects.java:136)
	at me.swirtzly.minecraft.angels.WeepingAngels.onNewRegistries(WeepingAngels.java:53)
	at net.minecraftforge.eventbus.ASMEventHandler_1_WeepingAngels_onNewRegistries_NewRegistry.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126)
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214)
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$22(ModLoader.java:202)
	at net.minecraftforge.registries.GameData.fireCreateRegistryEvents(GameData.java:948)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

[07Oct2020 21:15:38.147] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.NewRegistry dispatch for modid weeping_angels
java.lang.NoSuchMethodError: net.minecraftforge.registries.DeferredRegister.create(Lnet/minecraftforge/registries/IForgeRegistry;Ljava/lang/String;)Lnet/minecraftforge/registries/DeferredRegister;
	at me.swirtzly.minecraft.angels.common.WAObjects$Sounds.<clinit>(WAObjects.java:136) ~[?:1.0.1]
	at me.swirtzly.minecraft.angels.WeepingAngels.onNewRegistries(WeepingAngels.java:53) ~[?:1.0.1]
	at net.minecraftforge.eventbus.ASMEventHandler_1_WeepingAngels_onNewRegistries_NewRegistry.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) ~[?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) ~[?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$22(ModLoader.java:202) ~[?:?]
	at net.minecraftforge.registries.GameData.fireCreateRegistryEvents(GameData.java:948) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.2.0-launcher.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[07Oct2020 21:15:38.154] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CREATE_REGISTRIES, 1 errors found
[07Oct2020 21:15:38.155] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.2.0-launcher.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[07Oct2020 21:15:39.556] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[07Oct2020 21:15:39.657] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[07Oct2020 21:15:39.705] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\Bryan\Desktop\MultiMC\instances\weeping Angels Bug Test\.minecraft\config\forge-client.toml is not correct. Correcting
[07Oct2020 21:15:39.706] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client was corrected from null to SimpleCommentedConfig:{}
[07Oct2020 21:15:39.706] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.zoomInMissingModelTextInGui was corrected from null to false
[07Oct2020 21:15:39.707] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.forgeCloudsEnabled was corrected from null to true
[07Oct2020 21:15:39.707] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.disableStairSlabCulling was corrected from null to false
[07Oct2020 21:15:39.708] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.alwaysSetupTerrainOffThread was corrected from null to false
[07Oct2020 21:15:39.708] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.forgeLightPipelineEnabled was corrected from null to true
[07Oct2020 21:15:39.708] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.experimentalForgeLightPipelineEnabled was corrected from null to false
[07Oct2020 21:15:39.709] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.selectiveResourceReloadEnabled was corrected from null to true
[07Oct2020 21:15:39.709] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key client.showLoadWarnings was corrected from null to true
[07Oct2020 21:15:39.724] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\Bryan\Desktop\MultiMC\instances\weeping Angels Bug Test\.minecraft\config\weeping_angels-common.toml is not correct. Correcting
[07Oct2020 21:15:39.724] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen was corrected from null to SimpleCommentedConfig:{}
[07Oct2020 21:15:39.726] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen.arms was corrected from null to true
[07Oct2020 21:15:39.726] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen.genCatacombs was corrected from null to false
[07Oct2020 21:15:39.729] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen.chanceCatacombs was corrected from null to 25
[07Oct2020 21:15:39.731] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key world_gen.genOres was corrected from null to true
[07Oct2020 21:15:39.732] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn was corrected from null to SimpleCommentedConfig:{}
[07Oct2020 21:15:39.732] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.minimumSpawn was corrected from null to 1
[07Oct2020 21:15:39.733] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.maximumSpawn was corrected from null to 1
[07Oct2020 21:15:39.733] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.spawnWeight was corrected from null to 5
[07Oct2020 21:15:39.733] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.spawnType was corrected from null to MONSTER
[07Oct2020 21:15:39.733] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn.allowedBiomes was corrected from null to [minecraft:taiga_hills, minecraft:taiga, minecraft:desert, minecraft:desert_hills, minecraft:plains, minecraft:swamp, minecraft:beach, minecraft:snowy_taiga]
[07Oct2020 21:15:39.734] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel was corrected from null to SimpleCommentedConfig:{}
[07Oct2020 21:15:39.734] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.hardcoreMode was corrected from null to false
[07Oct2020 21:15:39.735] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.playScrapeSound was corrected from null to true
[07Oct2020 21:15:39.735] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.playSeenSounds was corrected from null to true
[07Oct2020 21:15:39.735] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.damage was corrected from null to 8.0
[07Oct2020 21:15:39.735] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.xpGained was corrected from null to 25
[07Oct2020 21:15:39.735] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.chickenGoboom was corrected from null to true
[07Oct2020 21:15:39.735] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.torchBlowOut was corrected from null to true
[07Oct2020 21:15:39.736] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.freezeOnAngel was corrected from null to false
[07Oct2020 21:15:39.736] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.pickaxeOnly was corrected from null to true
[07Oct2020 21:15:39.736] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.stalkRange was corrected from null to 65
[07Oct2020 21:15:39.736] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.moveSpeed was corrected from null to 1.5
[07Oct2020 21:15:39.736] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.blockBreaking was corrected from null to true
[07Oct2020 21:15:39.736] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.disAllowedBlocks was corrected from null to [minecraft:magma_block, minecraft:glowstone, minecraft:sea_lantern, tardis:exterior_steampunk, tardis:exterior_clock, minecraft:air]
[07Oct2020 21:15:39.737] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.blockBreakRange was corrected from null to 15
[07Oct2020 21:15:39.737] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key angel.transparentBlocks was corrected from null to []
[07Oct2020 21:15:39.738] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport was corrected from null to SimpleCommentedConfig:{}
[07Oct2020 21:15:39.738] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.teleportType was corrected from null to RANDOM_PLACE
[07Oct2020 21:15:39.738] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.notAllowedDimensions was corrected from null to [DimensionType{minecraft:the_end}]
[07Oct2020 21:15:39.738] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.justTeleport was corrected from null to false
[07Oct2020 21:15:39.738] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.teleportRange was corrected from null to 450
[07Oct2020 21:15:39.738] [Server-Worker-6/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key teleport.angelDimTeleport was corrected from null to true
[07Oct2020 21:15:39.740] [Server-Worker-6/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event SETUP, 1 errors found.
[07Oct2020 21:15:39.740] [Server-Worker-6/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event SETUP, 1 errors found
[07Oct2020 21:15:39.740] [Server-Worker-6/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[07Oct2020 21:15:41.801] [Server-Worker-7/ERROR] [net.minecraftforge.fml.ModLoader/LOADING]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[07Oct2020 21:15:41.802] [Server-Worker-7/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[07Oct2020 21:15:41.802] [Server-Worker-7/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.finishModLoading(ClientModLoader.java:137) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$4(ClientModLoader.java:107) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_261]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_261]
[07Oct2020 21:15:41.987] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[07Oct2020 21:15:41.988] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[07Oct2020 21:15:42.103] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[07Oct2020 21:15:42.193] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x4 minecraft:textures/atlas/signs.png-atlas
[07Oct2020 21:15:42.193] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[07Oct2020 21:15:42.194] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[07Oct2020 21:15:42.194] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[07Oct2020 21:15:42.195] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[07Oct2020 21:15:42.195] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[07Oct2020 21:15:42.507] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[07Oct2020 21:15:42.508] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[07Oct2020 21:15:42.508] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
"

**Comment by Jeryn99** [comment] 2020-10-08 06:16
Duplicate of https://github.com/WhoCraft/Weeping-Angels/issues/127

Please read through it and then update forge to latest.

**Closed as completed by Jeryn99** 2020-10-08 06:16 UTC
