### ISSUE TITLE
Assuming a compatibility issue with the mod Danny's expansion

### ISSUE THREAD

**Issue by HacoKavanah** [ReallySub/Weeping-Angels-Mod#168] opened 2021-07-13 21:30 UTC
The following crash occurs when world generation has reached 100%. Everything freezes and the logs state the game has crashed. I am playing on 1.16.2.

--- Minecraft Crash Report ----
// You're mean.

Time: 7/13/21 8:43 PM
Description: Ticking memory connection

java.lang.ClassCastException: me.suff.mc.angels.conversion.AngelInfection cannot be cast to com.bottomtextdanny.dannys_expansion.core.capabilities.player.DannyEntityCap
	at com.bottomtextdanny.dannys_expansion.core.Util.EntityUtil.getDannyCap(EntityUtil.java:27) ~[?:1.0.9] {re:classloading}
	at com.bottomtextdanny.dannys_expansion.core.events.TickHandler.onLogin(TickHandler.java:166) ~[?:1.0.9] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1121_TickHandler_onLogin_LoadFromFile.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2608/536466469.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoadingEvent(ForgeEventFactory.java:333) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.storage.PlayerData.func_237336_b_(PlayerData.java:58) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:294) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:PlayerListMixin,pl:mixin:APP:origins.mixins.json:LoginMixin,pl:mixin:APP:origins.forge.mixins.json:PlayerManagerMixin,pl:mixin:A}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:128) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:PlayerListMixin,pl:mixin:APP:origins.mixins.json:LoginMixin,pl:mixin:APP:origins.forge.mixins.json:PlayerManagerMixin,pl:mixin:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$19165/280080592.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by Jeryn99** [comment] 2021-07-13 21:33
Hi There,
This issue is a duplicate of #165
Please look at that issue for more information

**Closed as completed by Jeryn99** 2021-07-13 21:33 UTC
