### ISSUE TITLE
does not work in the new 1.19.2 update

### ISSUE THREAD

**Issue by Renowbrine** [ReallySub/Weeping-Angels-Mod#379] opened 2024-08-30 15:53 UTC
![image](https://github.com/user-attachments/assets/782d119b-0fe4-4332-a607-c4119ba7d486)

**Comment by Jeryn99** [comment] 2024-08-30 15:54
Duplicate of https://github.com/Jeryn99/Weeping-Angels/issues/375 and https://github.com/Jeryn99/Weeping-Angels/issues/376

Please track https://github.com/Jeryn99/Weeping-Angels/issues/376

**Closed as completed by Jeryn99** 2024-08-30 15:54 UTC
