### ISSUE TITLE
Weeping Angels and TARDIS Mod Dimension Crash

### ISSUE THREAD

**Issue by MianReplicate** [ReallySub/Weeping-Angels-Mod#264] opened 2022-10-12 23:51 UTC
Game Version: 1.16.5
ModLoader: Forge
Forge Version: 36.2.39
Weeping Angel Mod Version: 36.0.1
Tardis Mod Mod Version: 1.5.4

- What Happens?
When a WA is in the TARDIS and you attempt to change the dimension, SOMETIMES the game crashes. I don't see a reason as to why it happens but somehow it does.

- How to Reproduce
1. Change TARDIS dimension while Weeping Angel is inside
2. Game SHOULD crash, if it doesn't, land the TARDIS when the WA makes it take off. Then activate the components below, and repeat   steps until crash. EVENTUALLY it should crash.

Crash Log
[crash-2022-10-12_16.47.33-server.txt](https://github.com/Suff99/Weeping-Angels/files/9769312/crash-2022-10-12_16.47.33-server.txt)

Thanks in advance 👍

**Comment by Jeryn99** [comment] 2022-11-02 19:58
Duplicate of https://github.com/Suff99/Weeping-Angels/issues/262

**Closed as completed by Jeryn99** 2022-11-02 19:58 UTC
