### ISSUE TITLE
Tinker Construct Pickaxes Don't Work on Weeping Angels (1.16.5)

### ISSUE THREAD

**Issue by MianReplicate** [ReallySub/Weeping-Angels-Mod#263] opened 2022-10-12 23:13 UTC
MC Ver: 1.16.5
Forge Ver: 36.2.39
Weeping Angel Ver: 36.0.1
Tinkers Constructs Ver: 3.3.4.335
Mantle (DEPENDENCY FOR TINKERS) Ver: 1.6.157

- What Happens
Quite simply, using Tinker Construct default pickaxes/custom-made pickaxes just don't work at all on the Weeping Angels. 

I know that this has already been reported but it was for 1.18.2 so I wasn't sure whether to comment on that post about it for this version or just create a new one, sorry if that creates more work or angers you.

Thanks in advance 👍

**Comment by Jeryn99** [comment] 2022-11-02 19:59
Duplicate of https://github.com/Suff99/Weeping-Angels/issues/259
Merging issues as they come down to the same problem across versions

**Closed as completed by Jeryn99** 2022-11-02 19:59 UTC
