### ISSUE TITLE
Crashing when I see, I spawn, I place and makes the world unplayable if the mod still in work

### ISSUE THREAD

**Issue by scarsaliff** [ReallySub/Weeping-Angels-Mod#330] opened 2023-11-26 08:12 UTC
[crash-2023-11-26_11.07.13-client.txt](https://github.com/Suff99/Weeping-Angels/files/13466229/crash-2023-11-26_11.07.13-client.txt)

Please fix. I trying to play herobrine mods like but when I add this mod to my game it causes crash.

**Comment by scarsaliff** [comment] 2023-11-26 08:12
1.19.2, it happened me in 1.20.1 too.

**Comment by Jeryn99** [comment] 2023-11-26 11:52
Duplicate of https://github.com/Suff99/Weeping-Angels/issues/282

**Closed as completed by Jeryn99** 2023-11-26 11:52 UTC
