### ISSUE TITLE
Graveyards generate underneath terrain, waterlogged and carve out terrain.

### ISSUE THREAD

**Issue by Casterborous** [ReallySub/Weeping-Angels-Mod#167] opened 2021-07-11 02:34 UTC
Graveyards spawn intersecting the terrain, resembling a chunk error. Many blocks are waterlogged and often intersect with rivers.

Can confirm this error is independent of this mod, and not caused by any extra mods.
![2021-07-11_03 24 03](https://user-images.githubusercontent.com/77419793/125181026-c351f780-e1f8-11eb-9129-75217f4baf20.png)
![2021-07-11_03 24 11](https://user-images.githubusercontent.com/77419793/125181028-c64ce800-e1f8-11eb-8c86-623bbb2fc7d8.png)
![2021-07-11_03 24 27](https://user-images.githubusercontent.com/77419793/125181032-c9e06f00-e1f8-11eb-8b9f-ae0188c2a7c3.png)
![2021-07-11_03 28 40](https://user-images.githubusercontent.com/77419793/125181033-cc42c900-e1f8-11eb-8aec-f3819c82c037.png)
![2021-07-11_03 29 04](https://user-images.githubusercontent.com/77419793/125181034-ce0c8c80-e1f8-11eb-881d-21c773bedc6b.png)
![2021-07-11_03 32 06](https://user-images.githubusercontent.com/77419793/125181035-d06ee680-e1f8-11eb-9e85-ea4516708133.png)

**Comment by Jeryn99** [comment] 2021-07-11 18:53
Hey there,
I fixed this recently but I have not released it yet, as I have a few other things I want to do with Angels before I make a release 
I'm going to close this as the issue is already resolved, but thank you for reporting this issue to me

**Comment by Casterborous** [comment] 2021-07-11 20:55
> Hey there,
> I fixed this recently but I have not released it yet, as I have a few other things I want to do with Angels before I make a release
> I'm going to close this as the issue is already resolved, but thank you for reporting this issue to me

Thank you!

**Comment by Jeryn99** [comment] 2021-07-16 20:43
You can find the fixed version here, please let me know if the issue persists
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3391053

The issue will be present in existing structures and ones that have already been generated

**Comment by Casterborous** [comment] 2021-07-18 00:57
Its usually open to the air most of the time. But it's still sunken almost
entirely into the ground. and the protrusion where the mausoleum is causes
these square shaped voids in the ground.

**Comment by Jeryn99** [comment] 2021-07-18 08:17
Ah darn, looks like I need to look more into this one

**Comment by Casterborous** [comment] 2021-07-18 19:25
Thank you!

**Comment by Casterborous** [comment] 2021-07-18 19:25
definitely an improvement but still a lil buggy.

**Comment by Casterborous** [comment] 2021-07-19 20:54
Can I ask by the way, what causes players names to appear on gravestones?

**Comment by Jeryn99** [comment] 2021-07-19 21:03
There are no player names involved with the gravestones. They are all taken from inside the mod.
It is designed to work with data packs, you can find the list here: https://github.com/WhoCraft/Weeping-Angels/blob/1.16/src/main/resources/data/weeping_angels/names.json

**Comment by Casterborous** [comment] 2021-07-19 21:49
What?

I played on a server recently and every name glitched to be my username.

**Comment by Casterborous** [comment] 2021-07-19 21:50
Theres also "PLACEHOLDER" as a name

**Comment by Jeryn99** [comment] 2021-07-20 08:57
Could you show me the yard where you found the placeholder one? Looks like I missed a sign

**Comment by Casterborous** [comment] 2021-07-20 17:09
I cant rn, but its on the right, pretty close to the front gate as you walk
in, a couple of rows down.

**Closed as completed** 2022-04-16 10:13 UTC
Labels: wontfix, forge, 1.16, world-gen
