### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by avidbiscuit** [ReallySub/Weeping-Angels-Mod#184] opened 2021-10-07 15:43 UTC
**Crash Report + Latest.log:**
[crash-2021-10-07_16.37.30-server.txt](https://github.com/Suff99/Weeping-Angels/files/7305058/crash-2021-10-07_16.37.30-server.txt)
[latest.log](https://github.com/Suff99/Weeping-Angels/files/7305061/latest.log)
**Crash Description:**
When landing and attempting to exit the TARDIS and having the weeping angels mod installed the game crashes immediately. The mod version is Weeping-Angels-1.16.x-2.1.4, I have tested my world without the Weeping Angels mod installed and no issue has occurred. 
**Caused by: java.lang.NoClassDefFoundError: me/suff/mc/angels/common/tileentities/SnowArmTile$SnowAngelStages**

**Comment by Jeryn99** [comment] 2021-10-07 15:45
Hello,
Nothing to do with Tardis mod from what I can see, not too sure what's causing this
Also, I deleted your uncompleted issue, but you do know there's an edit button yeah?

This is an ongoing issue, I will keep looking into it, but I can't reproduce it

**Comment by Jeryn99** [comment] 2021-10-07 15:47
Notes: It appears this seems to happen with inner classes and not with normal classes, did I miss some obscure ForgeGradle update or something? @50ap5ud5

**Comment by avidbiscuit** [comment] 2021-10-07 15:47
> 
> 
> Hello, Nothing to do with Tardis mod from what I can see, not too sure what's causing this Also, I deleted your uncompleted issue, but you do know there's an edit button yeah?
> 
> This is an ongoing issue, I will keep looking into it, but I can't reproduce it

Only saw it after I created this issue! Will remember it in the future

**Comment by avidbiscuit** [comment] 2021-10-07 15:48
> 
> 
> Notes: It appears this seems to happen with inner classes and not with normal classes, did I miss some obscure ForgeGradle update or something? @50ap5ud5

https://stackoverflow.com/questions/17973970/how-can-i-solve-java-lang-noclassdeffounderror

This might help?

**Comment by Jeryn99** [comment] 2021-10-07 15:52
I appreciate the help, but I don't think it's anything to do with my actual code, but instead the compile process somewhere, I know what class not found is 

This issue has been reported before in https://github.com/Suff99/Weeping-Angels/issues/180 and was thought to be fixed with recompiling and releasing 

There seem to be two patterns, it happens with the Tardis mod installed, but it's not a fault on their side, but it also only happens for inner classes

**Comment by Jeryn99** [comment] 2021-10-13 07:39
Download: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3489307

Come back if the issue persists

**Closed as completed by Jeryn99** 2021-10-13 07:39 UTC
Labels: bug, 1.16
