### ISSUE TITLE
(1.20.1 Fabric) it crash when i see angels

### ISSUE THREAD

**Issue by LiqhtKillua** [ReallySub/Weeping-Angels-Mod#321] opened 2023-10-27 19:56 UTC
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: weeping_angels:textures/entity/angel/spare_time/variants/gas_stone/gas_stone_angel_\u0131dle.png
	at net.minecraft.class_2960.method_45137(class_2960.java:252)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at mc.craig.software.angels.client.models.entity.angel.GasAngelModel.texture(GasAngelModel.java:119)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.getTextureLocation(WeepingAngelRenderer.java:76)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.getRenderType(WeepingAngelRenderer.java:59)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.method_24302(WeepingAngelRenderer.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:136)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.render(WeepingAngelRenderer.java:53)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.method_3936(WeepingAngelRenderer.java:22)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2960.method_45137(class_2960.java:252)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at mc.craig.software.angels.client.models.entity.angel.GasAngelModel.texture(GasAngelModel.java:119)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.getTextureLocation(WeepingAngelRenderer.java:76)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.getRenderType(WeepingAngelRenderer.java:59)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.method_24302(WeepingAngelRenderer.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:136)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.render(WeepingAngelRenderer.java:53)
	at mc.craig.software.angels.client.render.entity.WeepingAngelRenderer.method_3936(WeepingAngelRenderer.java:22)
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Entity being rendered --
Details:
	Entity Type: weeping_angels:weeping_angel (mc.craig.software.angels.common.entity.angel.WeepingAngel)
	Entity ID: 27219
	Entity Name: Weeping Angel
	Entity's Exact location: -1568.50, 3.00, -652.50
	Entity's Block location: World: (-1569,3,-653), Section: (at 15,3,3 in -99,0,-41; chunk contains blocks -1584,-64,-656 to -1569,319,-641), Region: (-4,-2; contains chunks -128,-64 to -97,-33, blocks -2048,-64,-1024 to -1537,319,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: mc.craig.software.angels.client.render.entity.WeepingAngelRenderer@512a5548
	Location: -0.20,4.38,37.17 - World: (-1,4,37), Section: (at 15,4,5 in -1,0,2; chunk contains blocks -16,-64,32 to -1,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Rotation: 63.28125
	Delta: 0.90012795
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:145)
	at net.minecraft.class_761.method_22977(class_761.java:1574)
	at net.minecraft.class_761.method_22710(class_761.java:1324)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Jeryn99** [comment] 2023-11-26 11:51
Duplicate of https://github.com/Suff99/Weeping-Angels/issues/282

**Closed as completed by Jeryn99** 2023-11-26 11:51 UTC
