### ISSUE TITLE
Config doesn't work

### ISSUE THREAD

**Issue by masonclomid** [ReallySub/Weeping-Angels-Mod#224] opened 2022-05-22 17:49 UTC
Config "pickaxes and generators only" doesn't work, the angels will take damage from any source even if it's set to true.
Uesing version 3.0.1 in 1.16.5，forge36.2.20

**Comment by Jeryn99** [comment] 2022-05-22 18:03
Duplicate of https://github.com/Suff99/Weeping-Angels/issues/222
Please track that issue for updates

**Comment by Jeryn99** [comment] 2022-05-29 10:39
Nevermind, it seems that the duplicate issue is for 1.12 which is no longer supported

**Comment by Jeryn99** [comment] 2022-06-06 07:24
Hello, I'm going to need you config file, as I do not know what you mean by "set to true'

**Comment by masonclomid** [comment] 2022-06-17 12:56
Hello. With this configuration, the angels will still take damage from other than pickaxe and generator.
![234537113](https://user-images.githubusercontent.com/101992860/174302504-39389b84-2f4b-4e39-8449-9b4c8630c8dd.png)
![984314653](https://user-images.githubusercontent.com/101992860/174302542-ecf84b12-e8ee-4c24-81ea-10ef01894afd.png)

**Comment by Jeryn99** [comment] 2022-06-17 21:36
``pickaxeOnly`` is a legacy option, it seems I did not clean up unused config values; Sorry for that.
I have since worked on the issue you have shown and it seems it was just an oversight at the time

I have fixed this for 1.19, fixes for 1.18 and 1.16 will be coming soon

**Comment by masonclomid** [comment] 2022-06-18 04:24
Thanks for your work

**Comment by Jeryn99** [comment] 2022-07-09 11:18
Patched for 1.16 and 1.19

**Closed as completed by Jeryn99** 2022-07-09 11:18 UTC
Labels: 1.16, Other versions need address
