### ISSUE TITLE
[Fabric 1.21] RuntimeException on server 

### ISSUE THREAD

**Issue by 7Stay** [ReallySub/Weeping-Angels-Mod#368] opened 2024-07-23 07:00 UTC
Try on local it works perfectly fine but starting server with mod produce err as below:

caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
        at mc.craig.software.angels.network.WANetworkManager.make(WANetworkManager.java) ~[fabric-weeping_angels-mc1.21-v1.0.0.jar:?]
        at mc.craig.software.angels.network.WANetworkManager.<clinit>(WANetworkManager.java:24) ~[fabric-weeping_angels-mc1.21-v1.0.0.jar:?]
        at mc.craig.software.angels.WeepingAngels.init(WeepingAngels.java:45) ~[fabric-weeping_angels-mc1.21-v1.0.0.jar:?]
        at mc.craig.software.angels.fabric.WeepingAngelsFabric.onInitialize(WeepingAngelsFabric.java:54) ~[fabric-weeping_angels-mc1.21-v1.0.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.0.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.0.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at mc.craig.software.angels.network.WANetworkManager.make(WANetworkManager.java) ~[fabric-weeping_angels-mc1.21-v1.0.0.jar:?]
        at mc.craig.software.angels.network.WANetworkManager.<clinit>(WANetworkManager.java:24) ~[fabric-weeping_angels-mc1.21-v1.0.0.jar:?]
        at mc.craig.software.angels.WeepingAngels.init(WeepingAngels.java:45) ~[fabric-weeping_angels-mc1.21-v1.0.0.jar:?]
        at mc.craig.software.angels.fabric.WeepingAngelsFabric.onInitialize(WeepingAngelsFabric.java:54) ~[fabric-weeping_angels-mc1.21-v1.0.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)

**Comment by Jeryn99** [comment] 2024-07-23 09:51
Hello. Please ensure your issue is not already reported via the search bar before creating a new issue.

Duplicate of https://github.com/Jeryn99/Weeping-Angels/issues/366

**Closed as completed by Jeryn99** 2024-07-23 09:51 UTC

**Comment by koshnarek** [comment] 2024-07-23 12:35
@Jeryn99 btw.. great work with the mod! ;)

**Comment by 7Stay** [comment] 2024-07-23 12:44
> Hello. Please ensure your issue is not already reported via the search bar before creating a new issue.
> 
> Duplicate of #366

My bad I thought it was different issue, thanks.
