### ISSUE TITLE
Strange crash with The End 1.16.5

### ISSUE THREAD

**Issue by Lerrycapetime** [ReallySub/Weeping-Angels-Mod#192] opened 2021-10-19 04:48 UTC
Strange crash, when dying in The End and appearing in the overworld near a weeping angel causes crash. Also when entering The End portal and a weeping angel also jumps in after it'll attack you and crash the game. This is for 1.16.5
[crash-2021-10-18_21.42.06-server.txt](https://github.com/Suff99/Weeping-Angels/files/7370228/crash-2021-10-18_21.42.06-server.txt)
[crash-2021-10-18_21.37.18-server.txt](https://github.com/Suff99/Weeping-Angels/files/7370229/crash-2021-10-18_21.37.18-server.txt)

**Comment by Jeryn99** [comment] 2021-10-19 05:39
Duplicate of https://github.com/Suff99/Weeping-Angels/issues/190

**Closed as completed by Jeryn99** 2021-10-19 05:39 UTC

**Comment by Lerrycapetime** [comment] 2021-10-19 06:00
Ah ok! Glad it's getting resolved! thanks :)
