### ISSUE TITLE
Weeping angels crashing with Tardis Engineers 2

### ISSUE THREAD

**Issue by Thekiborg** [ReallySub/Weeping-Angels-Mod#191] opened 2021-10-17 13:05 UTC
I'm using Tardis Engineers 2 with Weeping Angels 2.1.5 and, when i get out of the tardis and i turn to close ithe door very fast, my game freezes and closes. This happened to me 3 times, 2 in the same spot and 1 in a different spot.

This is the crash for the first time i crashed: [crash-2021-10-16_18.53.19-server.txt](https://github.com/Suff99/Weeping-Angels/files/7359925/crash-2021-10-16_18.53.19-server.txt)
This is the second one: [crash-2021-10-16_18.58.15-server.txt](https://github.com/Suff99/Weeping-Angels/files/7359927/crash-2021-10-16_18.58.15-server.txt)
And this is the third: [crash-2021-10-16_19.36.07-server.txt](https://github.com/Suff99/Weeping-Angels/files/7359928/crash-2021-10-16_19.36.07-server.txt)

I'm uploading the 3 of them because i noticed the description was different in each one

**Comment by Jeryn99** [comment] 2021-10-17 13:06
Duplicate of #190

**Closed as completed by Jeryn99** 2021-10-17 13:06 UTC
