### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Revenge2K** [ReallySub/Weeping-Angels-Mod#380] opened 2024-08-31 22:28 UTC
When I run the game, it crashes and there is no crash report. Frankly, I have never been able to play this mode in a healthy way. In older versions it crashed while teleporting me. Or when I spawned it, it crashed. Now it doesn't open at all. No one knows for sure what causes this. (Forge 43.4.0) 1.19.2 (43.1.0 mod version)

Believe it or not, I would love to add this to my world's scariest modpack.

**Comment by Jeryn99** [comment] 2024-08-31 22:34
Duplicate of https://github.com/Jeryn99/Weeping-Angels/issues/376

You can go back a version for now
Please, in future provide crash reports and logs.

**Closed as completed by Jeryn99** 2024-08-31 22:34 UTC
